import type { ChatConversation, ChatMessage } from "./types";

export const mockConversations: ChatConversation[] = [
  {
    id: "conv-math-wang",
    kind: "direct",
    title: "Teacher Wang",
    subtitle: "Online and ready for remote support.",
    timeLabel: "10:32",
    unreadCount: 0,
    pinned: true,
    muted: false,
    participant: {
      id: "teacher-wang",
      name: "Teacher Wang",
      team: "Math",
      avatar: "W",
      presence: "online",
      presenceLabel: "Windows online",
      lastSeenLabel: "Active 10 minutes ago",
    },
  },
  {
    id: "conv-chinese-li",
    kind: "direct",
    title: "Teacher Li",
    subtitle: "Received, thank you.",
    timeLabel: "09:47",
    unreadCount: 9,
    pinned: false,
    muted: false,
    participant: {
      id: "teacher-li",
      name: "Teacher Li",
      team: "Chinese",
      avatar: "L",
      presence: "offline",
      presenceLabel: "Offline",
      lastSeenLabel: "Online yesterday",
    },
  },
  {
    id: "conv-english-zhang",
    kind: "direct",
    title: "Teacher Zhang",
    subtitle: "I will send the files later.",
    timeLabel: "09:12",
    unreadCount: 5,
    pinned: false,
    muted: false,
    participant: {
      id: "teacher-zhang",
      name: "Teacher Zhang",
      team: "English",
      avatar: "Z",
      presence: "away",
      presenceLabel: "Busy",
      lastSeenLabel: "In class",
    },
  },
  {
    id: "conv-physics-chen",
    kind: "direct",
    title: "Teacher Chen",
    subtitle: "[File] experiment-report-template.pdf",
    timeLabel: "Yesterday",
    unreadCount: 3,
    pinned: false,
    muted: false,
    participant: {
      id: "teacher-chen",
      name: "Teacher Chen",
      team: "Physics",
      avatar: "C",
      presence: "online",
      presenceLabel: "Windows online",
      lastSeenLabel: "Active just now",
    },
  },
  {
    id: "conv-admin",
    kind: "group",
    title: "Grade One Teaching Group",
    subtitle: "Please update this week's teaching schedule.",
    timeLabel: "Yesterday",
    unreadCount: 99,
    pinned: false,
    muted: false,
    participant: {
      id: "admin-group",
      name: "Grade One Teaching Group",
      team: "Academic Affairs",
      avatar: "G",
      presence: "online",
      presenceLabel: "Group active",
      lastSeenLabel: "12 members online",
    },
  },
  {
    id: "conv-office-device",
    kind: "device",
    title: "Office Device",
    subtitle: "Remote connection ended.",
    timeLabel: "Mon",
    unreadCount: 2,
    pinned: false,
    muted: false,
    participant: {
      id: "office-device",
      name: "Office Device",
      team: "Device",
      avatar: "PC",
      presence: "online",
      presenceLabel: "Device online",
      lastSeenLabel: "Active 4 minutes ago",
    },
  },
];

export const mockMessages: ChatMessage[] = [
  {
    id: "msg-time-1",
    conversationId: "conv-math-wang",
    kind: "system",
    content: "2026/06/22 10:28",
    timeLabel: "10:28",
  },
  {
    id: "msg-1",
    conversationId: "conv-math-wang",
    kind: "text",
    direction: "incoming",
    content: "Hello, can you help check today's schedule?",
    timeLabel: "10:30",
    senderId: 101,
  },
  {
    id: "msg-2",
    conversationId: "conv-math-wang",
    kind: "text",
    direction: "outgoing",
    content: "Sure. I will review it now.",
    timeLabel: "10:31",
    senderId: 1,
  },
  {
    id: "msg-3",
    conversationId: "conv-math-wang",
    kind: "file",
    direction: "incoming",
    content: "Weekly teaching plan.pdf",
    contentJson: {
      fileName: "Weekly teaching plan.pdf",
      sizeBytes: 248320,
    },
    timeLabel: "10:32",
    senderId: 101,
  },
  {
    id: "msg-admin-1",
    conversationId: "conv-admin",
    kind: "system",
    content: "Group chat created.",
    timeLabel: "Yesterday",
  },
  {
    id: "msg-admin-2",
    conversationId: "conv-admin",
    kind: "text",
    direction: "incoming",
    content: "Please update this week's teaching schedule.",
    timeLabel: "Yesterday",
    senderId: 102,
  },
  {
    id: "msg-admin-3",
    conversationId: "conv-admin",
    kind: "text",
    direction: "outgoing",
    content: "Received. I will update it today.",
    timeLabel: "Yesterday",
    senderId: 1,
  },
];
